set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[*] rgmii_rx_ctl rgmii_rxc}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[*] rgmii_tx_ctl rgmii_txc phy_reset_n}]
set_property PACKAGE_PIN A1 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN B3 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN A3 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN B4 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN A4 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN D4 [get_ports rgmii_rxc]
set_property PACKAGE_PIN E1 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN D1 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN F2 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN E2 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN F1 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN A2 [get_ports rgmii_txc]
set_property PACKAGE_PIN B1 [get_ports phy_reset_n]

set_property PACKAGE_PIN G3 [get_ports phy_mdc]
set_property PACKAGE_PIN F3 [get_ports phy_mdio]
set_property IOSTANDARD LVCMOS18 [get_ports {phy_mdc phy_mdio}]
set_property SLEW SLOW [get_ports {phy_mdc phy_mdio}]
